# Generated by Django 6.0.1 on 2026-02-24 21:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('campus', models.CharField(db_index=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('building_type', models.CharField(blank=True, max_length=255)),
                ('floors', models.IntegerField(default=0)),
                ('external_building_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('floor', models.IntegerField()),
                ('capacity', models.IntegerField(default=0)),
                ('room_type', models.CharField(blank=True, max_length=255)),
                ('room_type_id', models.IntegerField(blank=True, null=True)),
                ('room_code', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('floor_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('external_room_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.building')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('external_reservation_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('external_event_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('event_name', models.CharField(max_length=255)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status_id', models.SmallIntegerField(blank=True, null=True)),
                ('status_type_id', models.SmallIntegerField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('requires_check_in', models.BooleanField(default=False)),
                ('check_in_minutes', models.SmallIntegerField(default=0)),
                ('location_link', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='core.group')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.room')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.SmallIntegerField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('timezone', models.CharField(default='America/New_York', max_length=255)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='core.building')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('building', 'day_of_week'), name='uniq_building_day_hours')],
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['building', 'floor'], name='core_room_buildin_21244c_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('building', 'room_code'), name='uniq_roomcode_per_building'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['room', 'start_time'], name='core_reserv_room_id_e14e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['start_time', 'end_time'], name='core_reserv_start_t_9b7f13_idx'),
        ),
    ]
