# Generated by Django 6.0.1 on 2026-02-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='raw_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='group',
            name='raw_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='raw_event_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='raw_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
