# Generated by Django 6.0.1 on 2026-03-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_building_raw_name_group_raw_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
