# Generated by Django 6.0.1 on 2026-03-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_room_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
