# Generated by Django 6.0.1 on 2026-03-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
