# Generated by Django 6.0.1 on 2026-03-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_reservation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='external_event_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
