# Generated by Django 6.0.1 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_reservation_external_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="building",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
