# Generated by Django 6.0.1 on 2026-04-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_building_description_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='external_reservation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('external_reservation_id', 'room'), name='uniq_reservation_per_room'),
        ),
    ]
